### ISSUE TITLE
请问如何删除配方？

### ISSUE THREAD

**Issue by genelocated** [rime/plum#27]

**Comment by BlindingDark** [comment]
参考 [easy-en](https://github.com/BlindingDark/rime-easy-en) 删除方式

1. 删除位于 `plum/package/` 下的 easy_en git 仓库
1. 删除 `default.yaml` schema_list 中的 easy_en
1. 删除 `rime` 用户文件夹下 easy_en 开头的文件
1. 如果使用了混输，还需要删除对应方案的 `custom.yaml` 下 `__patch` 中的如下内容
   ```yaml
   # Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin {
     - patch/+:
         __include: easy_en:/patch
   # }
   ```
1. 重新部署 rime
