### ISSUE TITLE
設計配方定義文件的格式

### ISSUE THREAD

**Issue by lotem** [rime/plum#4]
1. 「配方」用於定義一組配置及其他數據文件，指定其如何使用。

2. 配方定義文件的格式有以下選擇：

- bash 腳本，可定義（實現）一組變量、函數
- 特定格式的 YAML 文件

無論哪種格式，都允許在代碼庫缺失配方定義文件的情況下，自動推導出默認的配方定義。
在 Windows 平臺 bash 不可用的情況下，只能忽略配方定義文件，做默認安裝。

3. 在配方裏定義安裝動作，有以下選擇：

- 安裝腳本（bash）
- 指定要複製的文件 + 打補靪

無論哪種形式，都支持在未定義安裝動作的情況下，執行默認的安裝動作。
目前已實現的默認安裝動作爲：複製代碼庫中的 `*.yaml, *.txt, opencc/*.{json,ocd,txt}` 文件。

4. 一份代碼庫可以提供多份配方。
安裝時指定配方 `user/repo:RECIPE` 或安裝代碼庫默認的配方 `user/repo`。

5. 參數化配方，允許在安裝時定義一組變量以改變（具體化）安裝動作。
例如爲某項用補靪實現的定製動作設定目標輸入方案。

若選用 bash 安裝腳本，則實現參數化比較容易；
若選用 YAML 格式的補靪，則需要模板機制。

**Comment by nameoverflow** [comment]
听起来不错， 但是似乎破坏了现在的方案机制的简洁性，方案本身和包管理器耦合起来了。
感觉如果在 /plum/ 中对配方定义做集中管理可以减轻对方案制定的负担，就像 [homebrew](https://github.com/Homebrew/homebrew-core/tree/master/Formula) 做的一样。

**Comment by lotem** [comment]
我還考慮過一個加強版的無配方文件的簡易實現：
規範 `*.custom.yaml` 的格式，安裝時合併 `*.custom.yaml` 的內容，而非簡單地複製文件。
因爲有賴於打補靪實現的配方包之間，很容易發生同名補靪文件相互覆蓋的錯誤。

合併 `*.custom.yaml` 文件的具體方法是跳過文件開頭的註釋行，讀到 `^patch:$` 之後，把剩餘的縮進代碼追加到已有的補靪文件。如果考慮到 `patch:` 以外會有其他的一級節點，則需要一點點腳本功夫。
這些編輯操作用 bash, sed, awk 可以完成。Windows 的做法需要研究。

或者不用文本操作實現。升級一下 `rime_patch` 程序，妥善地合併 YAML 補靪文件。只不過這樣會依賴於 `librime-tools`。

Node.js 也可以用來執行文本編輯操作；調 YAML 組件需要研究除了 exe 以外得安裝多大的 node_modules。

**Comment by lotem** [comment]
@nameoverflow 集中管理有他的好處，查詢下載都方便；也有潛在問題，就是不夠自由。一些用家可能只想整理歸納自用的方案和配置。
還有就是那個中心的維護成本、用戶更新代碼再提交 PR 更新配方的不便，幾乎超出了 Rime 用戶羣的承受力（homebrew 軟件包的維護者是與 Rime 開發者同級別的，更付得起辛苦成本）。

我認爲沒有中心，才能實現用戶僅通過維護一份配方列表實現終極配置。
去中心化輔以在「中心」以 user/repo 登記資源，就安穩了。

**Comment by LEOYoon-Tsaw** [comment]
用bash吧，畢竟更靈活，要能自動改名，例如提供一個xxx.schema.custom.yaml，然後根據提供的參數來確定xxx

**Comment by lotem** [comment]
草稿：（大體實現 https://github.com/rime-aca/OpenCC_Emoji ，加入了演示一些其他功能的代碼）
``` yaml
# encoding: utf-8
---
recipe:
  Rx: emoji-suggestion
  args:
    - schema=luna_pinyin
    - opt_extra_argument
  description: >-
    Show emoji suggestion with OpenCC
  # excludes:
  # includes:
  install_files: >-
    *.schema.yaml
    *.dict.yaml
    *.txt
    opencc/*.*
  patch_files:
    - recipe.yaml: ${schema:-luna_pinyin}.custom.yaml

patch:
  switches/+:
    - name: emoji_suggestion
      reset: 1
      states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  engine/filters/+:
    - simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
...

# recipe: luna-pinyin:enable
# recipe: util:enable-schema#schema=luna_pinyin
# recipe: util:select-schema#schema=luna_pinyin

--- | # this is how to apply patch to multiple files
recipe:
  patch:
    - recipe.yaml: luna_pinyin.custom.yaml
    - recipe.yaml: luna_pinyin_fluency.custom.yaml
    - recipe.yaml: luna_quanpin.custom.yaml
...
```

**Comment by lotem** [comment]
就 opencc emoji 這個例子來看，很可能需要一個專門打補靪用的配方，因爲需要給每個輸入方案都打上補靪，於是要分多次調用，每次給不同的 `schema` 參數。而複製 `opencc/*.*` 文件只需要一次。

所用配方大概是這樣的（`Rx` 代表給 `rime-install` 命令的配方參數）：

```
Rx emoji-suggestion  # 只安裝文件（emoji-suggestion:opencc ？）
Rx emoji-suggestion:patch#schema=luna_pinyin
Rx emoji-suggestion:patch#schema=cangjie5
...
```

**Comment by LEOYoon-Tsaw** [comment]
有幾個問題：
1. 如果複製文件時，發現重名文件怎麼辦，最優的做法可能是報警告，繼續執行，並不覆寫？同時bash指令允許用戶自行用argument指定覆寫行爲
1. `recipe/install_files`下是如何指定安裝路徑的？逐個匹配文件名，符合要求則放入相當位置／還是在repo裏面就要按照目標路徑放置文件？
1. `patch`下的內容如果與`recipe/patch_files`衝突，優先級？可以考慮報警告，中止執行，同時允許用戶自行用argument指定覆寫行爲

**Comment by lotem** [comment]
先找人用 bash 腳本實現一個簡單的用用看。
想要完善一些的話，我感覺 bash 很快就會不夠用了。
再考慮到多數 Windows 用戶不具有 bash，用嚴肅代碼實現配置管理器將有必要。

**Comment by lotem** [comment]
稍稍細化 `patch_files` 的語法

```yaml
patch_files:
  文件名甲:
    - 補靪一
    - 補靪二
  文件名乙:
    - 補靪三
```

補靪行及其下縮進行原樣（也考慮做字符串模板展開）追加到目標文件根節點的 `__patch` 節點下（若無 `__patch` 節點則添加）。腳本實現會非常簡單，且靈活度高。
並約定：一律寫作以 `-` 開頭的補靪列表，以避免出現應用多份補靪後出現 YAML key 重複的錯誤。

示例：

```yaml
# emoji_suggestion.recipe.yaml
# encoding: utf-8

---
recipe:
  Rx: emoji_suggestion
  args:
    - schema=luna_pinyin
  description: >-
    Customize input schema to show emoji suggestion with OpenCC

patch_files:
  ${schema:-luna_pinyin}.custom.yaml:
    - patch/+:
        __include: emoji_suggestion.recipe:/patch

patch:
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
```

配置管理器修改後的文件：

```yaml
# encoding: utf-8
__patch:
  # Rx opencc-emoji:emoji_suggestion {
    - patch/+:
        __include: emoji_suggestion.recipe:/patch
  # }
```

更多示例：

```yaml
patch_files:
  # This is possible but as always we recommend
  # putting user customization in luna_pinyin.custom.yaml, default.custom.yaml
  ${schema:-luna_pinyin}.schema.yaml:
    - ${schema:-luna_pinyin}.custom:/patch
    - emoji_suggestion.recipe:/patch
  default.yaml:
    - schema_list/=: []
    - schema_list/+:
      - schema: luna_pinyin
    - schema_list/+:
      - schema: combo_pinyin_kbcon
    - menu/page_size: 9
  default.custom.yaml:
    - patch/+:
        menu/page_size: 10
```
