### ISSUE TITLE
【咨询】两个patch如果有相同的 Key应该如何处理

### ISSUE THREAD

**Issue by vlaw** [rime/plum#67]
有如下的俩个文件

```yaml
# patch#1: emoji_suggestion
patch:
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: ["🈚️", "🈶️"]
```

```yaml
# patch#2: symbol_suggestion
patch:
  switches/@next: # 猜测是先合并
    name: symbol_support
    reset: 1
    states: [ "无符", "符" ]
```

```yaml
__patch:
  - patch/+:
      __include: emoji_suggestion:/patch
 - patch/+:
      __include: symbol_suggestion:/patch
```

预期：都以 追加的方式合并的编译后的文件中
实际效果：后者覆盖了前者
